### ISSUE TITLE
[BUG] `install` failing for some fMRIPrep data

### ISSUE THREAD

**Issue by michellewang** [neurodatascience/cohort_creator#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Dataset is downloaded from OpenNeuro.

### Current Behavior

Getting an error message for these datasets: `ds002158`, `ds002785`, `ds002790`, `ds002799`, `ds003452`, `ds003495`, `ds003798`. Other datasets with fMRIPrep data (e.g. `ds000208`, `ds000220`) seem to work fine.

### Error message

Example error:
```
Traceback (most recent call last):
  File "/data/origami/michelle/miniconda3/envs/nilearn/bin/cohort_creator", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/data/origami/michelle/miniconda3/envs/nilearn/lib/python3.11/site-packages/cohort_creator/_cli.py", line 79, in cli
    _execute_install(dataset_listing, args, output_dir)
  File "/data/origami/michelle/miniconda3/envs/nilearn/lib/python3.11/site-packages/cohort_creator/_cli.py", line 134, in _execute_install
    install_datasets(
  File "/data/origami/michelle/miniconda3/envs/nilearn/lib/python3.11/site-packages/cohort_creator/cohort_creator.py", line 79, in install_datasets
    _install(dataset_name=dataset_, dataset_types=dataset_types, output_dir=output_dir)
  File "/data/origami/michelle/miniconda3/envs/nilearn/lib/python3.11/site-packages/cohort_creator/cohort_creator.py", line 107, in _install
    api.install(path=data_pth, source=uri, dataset=api.Dataset(output_dir))
  File "/data/origami/michelle/miniconda3/envs/nilearn/lib/python3.11/site-packages/datalad/interface/base.py", line 773, in eval_func
    return return_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/origami/michelle/miniconda3/envs/nilearn/lib/python3.11/site-packages/datalad/interface/base.py", line 763, in return_func
    results = list(results)
              ^^^^^^^^^^^^^
  File "/data/origami/michelle/miniconda3/envs/nilearn/lib/python3.11/site-packages/datalad/interface/base.py", line 940, in _execute_command_
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'install',
  'message': ('Failed to clone from any candidate source URL. Encountered '
              'errors per each url were:\n'
              '- %s',
              'https://github.com/OpenNeuroDatasets/ds002158-tree-main-derivatives-fmriprep\n'
              "  CommandError: 'git -c diff.ignoreSubmodules=none -c "
              'core.quotepath=false clone --progress '
              'https://github.com/OpenNeuroDatasets/ds002158-tree-main-derivatives-fmriprep '
              "/data/origami/michelle/projects/nilearn/glm_experiments/outputs/sourcedata/ds002158-fmriprep' "
              "failed with exitcode 128 [err: 'Cloning into "
              "'/data/origami/michelle/projects/nilearn/glm_experiments/outputs/sourcedata/ds002158-fmriprep'...\n"
              'remote: Repository not found.\n'
              'fatal: repository '
              "'https://github.com/OpenNeuroDatasets/ds002158-tree-main-derivatives-fmriprep/' "
              "not found']\n"
              '- '
              'https://github.com/OpenNeuroDatasets/ds002158-tree-main-derivatives-fmriprep/.git\n'
              "  CommandError: 'git -c diff.ignoreSubmodules=none -c "
              'core.quotepath=false clone --progress '
              'https://github.com/OpenNeuroDatasets/ds002158-tree-main-derivatives-fmriprep/.git '
              "/data/origami/michelle/projects/nilearn/glm_experiments/outputs/sourcedata/ds002158-fmriprep' "
              "failed with exitcode 128 [err: 'Cloning into "
              "'/data/origami/michelle/projects/nilearn/glm_experiments/outputs/sourcedata/ds002158-fmriprep'...\n"
              'remote: Not Found\n'
              'fatal: repository '
              "'https://github.com/OpenNeuroDatasets/ds002158-tree-main-derivatives-fmriprep/.git/' "
              "not found']"),
  'path': '/data/origami/michelle/projects/nilearn/glm_experiments/outputs/sourcedata/ds002158-fmriprep',
  'refds': '/data/origami/michelle/projects/nilearn/glm_experiments/outputs',
  'source': {'default_destpath': 'ds002158-tree-main-derivatives-fmriprep',
             'giturl': 'https://github.com/OpenNeuroDatasets/ds002158-tree-main-derivatives-fmriprep/.git',
             'source': 'https://github.com/OpenNeuroDatasets/ds002158-tree-main-derivatives-fmriprep',
             'type': 'giturl',
             'version': None},
  'source_url': 'https://github.com/OpenNeuroDatasets/ds002158/tree/main/derivatives/fmriprep',
  'status': 'error',
  'type': 'dataset'}]
```

Pretty sure the other datasets that fail to install get the same error.

### Environment

- OS: Ubuntu 18.04.6 LTS
- Python version: 3.11.7
- `cohort_creator` version: 0.2.0

### How to reproduce

```
cohort_creator install -d datasets_results.tsv -o outputs/ --dataset_types fmriprep --generate_participant_listing
```

where `datasets_results.tsv` is something like:
```
DatasetID	PortalURI	NumMatchingSubjects	AvailableImageModalites	sessions	tasks	fmriprep	mriqc
ds002158	https://github.com/OpenNeuroDatasets/ds002158	20	['anat', 'eeg', 'fmap', 'func']	['001']	['main', 'rest']	https://github.com/OpenNeuroDatasets/ds002158/tree/main/derivatives/fmriprep	False
```

### Anything else?

Getting the same error on Compute Canada (`narval.computecanada.ca`):
- OS: Rocky Linux 8.9
- Python version: 3.11.5
- `cohort_creator` version: 0.2.0

**Comment by Remi-Gau** [comment]
ha yes I had forgotten to open an issue to remember about this.

for some datasets the derivatives are not on openneuro derivatives but in a subfolder of the openneuro datasets:

on openneuro derivatives
https://github.com/OpenNeuroDerivatives/ds000001-fmriprep

on openneuro
https://github.com/OpenNeuroDatasets/ds002799/tree/main/derivatives/fmriprep

but my code does not take this difference into account...

**Comment by Remi-Gau** [comment]
OK could fix the install but now need to fix the get and copy part

**Comment by Remi-Gau** [comment]
`rant mode: ON`

I love it when people dump preprocessed files in an fmriprep sub folder but:
- rename the files
- only put a subset of the files

Why do we bother standardizing filenames?

That won't mess parsing assumptions at all? ever? right?

`rant mode: OFF`

**Comment by Remi-Gau** [comment]
https://github.com/all-contributors please add @michellewang for userTesting

**Comment by Remi-Gau** [comment]
@all-contributors please add @michellewang for userTesting
