### ISSUE TITLE
[BUG] cannot install

### ISSUE THREAD

**Issue by Remi-Gau** [neurodatascience/cohort_creator#181]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Expected Behavior

install should work

### Error message

```
[12:06:40] INFO      http://neurobagel.org/vocab/022bb7c0-106e-4626-9b01-742f283aa61c                                                   main.py:81
           WARNING    http://neurobagel.org/vocab/022bb7c0-106e-4626-9b01-742f283aa61c not found in list of known datasets              main.py:95
           INFO      http://neurobagel.org/vocab/092b65bf-e04f-4016-af64-ed527c6f362a                                                   main.py:81
           WARNING    http://neurobagel.org/vocab/092b65bf-e04f-4016-af64-ed527c6f362a not found in list of known datasets              main.py:95
           INFO      http://neurobagel.org/vocab/1e52a752-1a90-4f98-9fa6-5ecb5f51f4f6                                                   main.py:81
           WARNING    http://neurobagel.org/vocab/1e52a752-1a90-4f98-9fa6-5ecb5f51f4f6 not found in list of known datasets              main.py:95
           INFO      http://neurobagel.org/vocab/37578ca8-9577-4cdf-9716-55f21b698015                                                   main.py:81
           WARNING    http://neurobagel.org/vocab/37578ca8-9577-4cdf-9716-55f21b698015 not found in list of known datasets              main.py:95
           INFO      http://neurobagel.org/vocab/6a64d375-efd7-45b2-8c3d-d684cc55358f                                                   main.py:81
           WARNING    http://neurobagel.org/vocab/6a64d375-efd7-45b2-8c3d-d684cc55358f not found in list of known datasets              main.py:95
           INFO      http://neurobagel.org/vocab/71044f64-fe97-4324-903d-7185f384fa26                                                   main.py:81
           WARNING    http://neurobagel.org/vocab/71044f64-fe97-4324-903d-7185f384fa26 not found in list of known datasets              main.py:95
           INFO      http://neurobagel.org/vocab/74966e22-ed20-4ff6-8b96-d63e87f3493a                                                   main.py:81
           WARNING    http://neurobagel.org/vocab/74966e22-ed20-4ff6-8b96-d63e87f3493a not found in list of known datasets              main.py:95
           INFO      http://neurobagel.org/vocab/76fb11c7-841d-41ef-b994-198976a5f16d                                                   main.py:81
           WARNING    http://neurobagel.org/vocab/76fb11c7-841d-41ef-b994-198976a5f16d not found in list of known datasets              main.py:95
           INFO      http://neurobagel.org/vocab/8afb4a3c-e863-4d3b-9247-1e22f0cabef7                                                   main.py:81
           WARNING    http://neurobagel.org/vocab/8afb4a3c-e863-4d3b-9247-1e22f0cabef7 not found in list of known datasets              main.py:95
           INFO      http://neurobagel.org/vocab/d2e1a31b-3762-4dbe-9c32-3444af7b127d                                                   main.py:81
           WARNING    http://neurobagel.org/vocab/d2e1a31b-3762-4dbe-9c32-3444af7b127d not found in list of known datasets              main.py:95
Installing datasets   0:00:00 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/10 100% 0:00:00
           INFO      Getting pybids layout of the following datasets: http://neurobagel.org/vocab/d2e1a31b-3762-4dbe-9c32-3444af7b127d  main.py:86
Traceback (most recent call last):
  File "/home/remi/miniconda3/bin/cohort_creator", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/remi/github/origami/cohort_creator/cohort_creator/_cli.py", line 96, in cli
    _execute_install(dataset_listing, args, output_dir)
  File "/home/remi/github/origami/cohort_creator/cohort_creator/_cli.py", line 162, in _execute_install
    install_datasets(
  File "/home/remi/github/origami/cohort_creator/cohort_creator/main.py", line 88, in install_datasets
    create_tsv_participant_session_in_datasets(
  File "/home/remi/github/origami/cohort_creator/cohort_creator/_utils.py", line 43, in create_tsv_participant_session_in_datasets
    layout = BIDSLayout(dataset)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/remi/miniconda3/lib/python3.11/site-packages/bids/layout/layout.py", line 128, in __init__
    root, description = validate_root(root, validate)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/miniconda3/lib/python3.11/site-packages/bids/layout/validation.py", line 70, in validate_root
    raise ValueError("BIDS root does not exist: %s" % root)
ValueError: BIDS root does not exist: /home/remi/github/origami/cohort_creator/outputs/sourcedata/http:/neurobagel.org/vocab/022bb7c0-106e-4626-9b01-742f283aa61c
```

### How to reproduce

use this tsv file

```
DatasetID	DatasetName	PortalURI	NumMatchingSubjects	AvailableImageModalities
http://neurobagel.org/vocab/022bb7c0-106e-4626-9b01-742f283aa61c	A longitudinal neuroimaging dataset on language processing in children ages 5, 7, and 9 years old	https://github.com/OpenNeuroDatasets-JSONLD/ds003604.git	155	http://purl.org/nidash/nidm#T1Weighted, http://purl.org/nidash/nidm#FlowWeighted, http://purl.org/nidash/nidm#DiffusionWeighted
http://neurobagel.org/vocab/092b65bf-e04f-4016-af64-ed527c6f362a	Goal-directed motor task	https://github.com/OpenNeuroDatasets-JSONLD/ds004056.git	29	http://purl.org/nidash/nidm#T1Weighted, http://purl.org/nidash/nidm#FlowWeighted, http://purl.org/nidash/nidm#T2Weighted
http://neurobagel.org/vocab/1e52a752-1a90-4f98-9fa6-5ecb5f51f4f6	Cost Analysis TBI	https://github.com/OpenNeuroDatasets-JSONLD/ds000220.git	26	http://purl.org/nidash/nidm#T1Weighted, http://purl.org/nidash/nidm#FlowWeighted
http://neurobagel.org/vocab/37578ca8-9577-4cdf-9716-55f21b698015	Queensland Twin IMaging (QTIM)	https://github.com/OpenNeuroDatasets-JSONLD/ds004169.git	140	http://purl.org/nidash/nidm#T1Weighted, http://purl.org/nidash/nidm#FlowWeighted
http://neurobagel.org/vocab/6a64d375-efd7-45b2-8c3d-d684cc55358f	The influence of heart rate variability biofeedback on cardiac regulation and functional brain connectivity	https://github.com/OpenNeuroDatasets-JSONLD/ds003357.git	32	http://purl.org/nidash/nidm#T1Weighted, http://purl.org/nidash/nidm#FlowWeighted
http://neurobagel.org/vocab/71044f64-fe97-4324-903d-7185f384fa26	Cortical myelin measured by the T1w/T2w ratio in individuals with depressive disorders and healthy controls 	https://github.com/OpenNeuroDatasets-JSONLD/ds003653.git	1	http://purl.org/nidash/nidm#T1Weighted, http://purl.org/nidash/nidm#T2Weighted
http://neurobagel.org/vocab/74966e22-ed20-4ff6-8b96-d63e87f3493a	Myconnectome	https://github.com/OpenNeuroDatasets-JSONLD/ds000031.git	1	http://purl.org/nidash/nidm#T1Weighted, http://purl.org/nidash/nidm#DiffusionWeighted, http://purl.org/nidash/nidm#T2Weighted, http://purl.org/nidash/nidm#FlowWeighted
http://neurobagel.org/vocab/76fb11c7-841d-41ef-b994-198976a5f16d	The Midnight Scan Club (MSC) dataset	https://github.com/OpenNeuroDatasets-JSONLD/ds000224.git	10	http://purl.org/nidash/nidm#FlowWeighted, http://purl.org/nidash/nidm#T1Weighted, http://purl.org/nidash/nidm#T2Weighted
http://neurobagel.org/vocab/8afb4a3c-e863-4d3b-9247-1e22f0cabef7	The Stockholm Sleepy Brain Study: Effects of Sleep Deprivation on Cognitive and Emotional Processing in Young and Old	https://github.com/OpenNeuroDatasets-JSONLD/ds000201.git	81	http://purl.org/nidash/nidm#T1Weighted, http://purl.org/nidash/nidm#T2Weighted, http://purl.org/nidash/nidm#FlowWeighted, http://purl.org/nidash/nidm#DiffusionWeighted
http://neurobagel.org/vocab/d2e1a31b-3762-4dbe-9c32-3444af7b127d	Auditory localization with 7T fMRI	https://github.com/OpenNeuroDatasets-JSONLD/ds001942.git	10	http://purl.org/nidash/nidm#T1Weighted, http://purl.org/nidash/nidm#DiffusionWeighted, http://purl.org/nidash/nidm#FlowWeighted
```

run

```
cohort_creator install -d dataset-level-results.tsv  --dataset_types raw -o outputs 
```

**Comment by Remi-Gau** [comment]
this bug does not happen if a participant list is passed with the dataset listing

```bash
cohort_creator install -d dataset-level-results.tsv  --dataset_types raw -o outputs -p participant-level-results.tsv 
```
