### ISSUE TITLE
ensure func confounds are got and copied

### ISSUE THREAD

**Issue by Remi-Gau** [neurodatascience/cohort_creator#201]

**Comment by Remi-Gau** [comment]
@michellewang 
I checked and I have test to get confounds that should follow the latest vesions of fmriprep.

Can you tell me for which datasets the confounds were not grabbed.

**Comment by michellewang** [comment]
@Remi-Gau it's for `study-ds000208` which has fMRIPrep 21.0.2. The confound timeseries have filenames that look like `sub-01_task-rest_desc-confounds_timeseries.tsv`

**Comment by Remi-Gau** [comment]
I can't seem to be able to reproduce the error.


TSV inputs used:

[input.zip](https://github.com/neurodatascience/cohort_creator/files/14746072/input.zip)

commands run

```bash
cohort_creator install -d tests/data/datasets_copy.tsv -p tmp/code/participants.tsv --dataset_types raw fmriprep -o tmp
cohort_creator get -d tests/data/datasets_copy.tsv -p tests/data/participants_copy.tsv  --dataset_types raw fmriprep -o tmp --datatype func
cohort_creator copy -d tests/data/datasets_copy.tsv -p tests/data/participants_copy.tsv  --dataset_types raw fmriprep -o tmp --datatype func
```

The confounds are there:

```bash
$ ls -l  tmp/study-ds000208/derivatives/fmriprep-21.0.2/sub-03/func/
total 352236
-r--r--r-- 1 remi remi     44059 mars  25 11:34 sub-03_task-rest_desc-confounds_timeseries.json
-r--r--r-- 1 remi remi    901257 mars  25 11:34 sub-03_task-rest_desc-confounds_timeseries.tsv
-rw-rw-r-- 1 remi remi       108 mars  25 11:34 sub-03_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.json
-r--r--r-- 1 remi remi 359728416 mars  25 11:34 sub-03_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.gz
```

Can you try to see if you get the same result?

**Comment by michellewang** [comment]
@Remi-Gau I just ran this and can confirm that I am able to get the timeseries...

Not sure if it mattered but I was on `0.2.0` and just reinstalled from `main` (which I hadn't done before because of issues on Compute Canada with one of the dependencies of `datalad-fuse`, but I managed to get around that). 

Also: I had to rerun some of the commands several times because of `git-annex` errors. At one point I only had partial results (only the confound timeseries, no images) so that might be why I was missing files originally...

Will try again on the whole dataset now.

**Comment by michellewang** [comment]
I keep getting the same `git-annex` error for `cohort_creator get`:
```
Traceback (most recent call last):
  File "/home/mwang8/envs/nilearn/bin/cohort_creator", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/lustre06/project/6018311/mwang8/projects/cohort_creator/cohort_creator/_cli.py", line 119, in cli
    get_data(
  File "/lustre06/project/6018311/mwang8/projects/cohort_creator/cohort_creator/main.py", line 221, in get_data
    _get_data_this_subject(
  File "/lustre06/project/6018311/mwang8/projects/cohort_creator/cohort_creator/main.py", line 294, in _get_data_this_subject
    dl_dataset.get(path=files, jobs=jobs, result_renderer="disabled")
  File "/home/mwang8/envs/nilearn/lib/python3.11/site-packages/datalad/distribution/dataset.py", line 507, in apply_func
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/mwang8/envs/nilearn/lib/python3.11/site-packages/datalad/interface/base.py", line 773, in eval_func
    return return_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mwang8/envs/nilearn/lib/python3.11/site-packages/datalad/interface/base.py", line 763, in return_func
    results = list(results)
              ^^^^^^^^^^^^^
  File "/home/mwang8/envs/nilearn/lib/python3.11/site-packages/datalad/interface/base.py", line 873, in _execute_command_
    for r in _process_results(
  File "/home/mwang8/envs/nilearn/lib/python3.11/site-packages/datalad/interface/utils.py", line 319, in _process_results
    for res in results:
  File "/home/mwang8/envs/nilearn/lib/python3.11/site-packages/datalad/distribution/get.py", line 1009, in __call__
    for res in _get_targetpaths(
  File "/home/mwang8/envs/nilearn/lib/python3.11/site-packages/datalad/distribution/get.py", line 674, in _get_targetpaths
    results = ds_repo.get(
              ^^^^^^^^^^^^
  File "/home/mwang8/envs/nilearn/lib/python3.11/site-packages/datalad/support/gitrepo.py", line 365, in _wrap_normalize_paths
    result = func(self, files_new, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mwang8/envs/nilearn/lib/python3.11/site-packages/datalad/support/annexrepo.py", line 1616, in get
    results = self._call_annex_records(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mwang8/envs/nilearn/lib/python3.11/site-packages/datalad/support/annexrepo.py", line 1133, in _call_annex_records
    raise e
  File "/home/mwang8/envs/nilearn/lib/python3.11/site-packages/datalad/support/annexrepo.py", line 1093, in _call_annex_records
    out = self._call_annex(
          ^^^^^^^^^^^^^^^^^
  File "/home/mwang8/envs/nilearn/lib/python3.11/site-packages/datalad/support/annexrepo.py", line 989, in _call_annex
    return runner.run_on_filelist_chunks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mwang8/envs/nilearn/lib/python3.11/site-packages/datalad/runner/gitrunner.py", line 256, in run_on_filelist_chunks
    for res in self._get_chunked_results(cmd=cmd,
  File "/home/mwang8/envs/nilearn/lib/python3.11/site-packages/datalad/runner/gitrunner.py", line 184, in _get_chunked_results
    yield self.run(
          ^^^^^^^^^
  File "/home/mwang8/envs/nilearn/lib/python3.11/site-packages/datalad/runner/runner.py", line 242, in run
    raise CommandError(
datalad.runner.exception.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none -c core.quotepath=false annex get -c annex.retry=3 --json --json-error-messages --json-progress -c annex.dotfiles=true -J6 -- sub-08/func/sub-08_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.gz sub-08/func/sub-08_task-rest_desc-confounds_timeseries.tsv sub-08/func/sub-08_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.json sub-08/func/sub-08_task-rest_desc-confounds_timeseries.json' failed with exitcode 135 under /lustre06/project/6018311/mwang8/projects/glm_experiments/troubleshoot/tmp/sourcedata/ds000208-fmriprep [info keys: stdout_json] [err: 'error: git-annex died of signal 7']
```

Interestingly, the error seems to be thrown only *after* a file is obtained successfully, and if I rerun the same command another file is downloaded (before the same error is thrown). So I am now running `cohort_creator get` in a loop for each participant until it stops failing, and it seems to be able to get all 4 files 😅

**Comment by Remi-Gau** [comment]
Wow. We found a new way to keep you busy.

By any chance do you know if you get those errors when using the datalad CLI directly?

**Comment by michellewang** [comment]
Yes I get the same error with e.g. `datalad get tmp/sourcedata/ds000208-fmriprep/sub-76/func/sub-76_task-rest_desc-confounds_timeseries.tsv` on the command-line
